// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbHd6NI4vW4KRwm1Z2dY-h0wmTmiKTH_Q',
    appId: '1:894628467468:web:13e8dbe411e9e279b32f29',
    messagingSenderId: '894628467468',
    projectId: 'flutter-project-fc411',
    authDomain: 'flutter-project-fc411.firebaseapp.com',
    databaseURL: 'https://flutter-project-fc411-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-project-fc411.appspot.com',
    measurementId: 'G-VMQZXTWMR2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7hrEUHmbUnUYpVBit8fsG3Z_0NtSdyvI',
    appId: '1:894628467468:android:6263b174bf5ad050b32f29',
    messagingSenderId: '894628467468',
    projectId: 'flutter-project-fc411',
    databaseURL: 'https://flutter-project-fc411-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-project-fc411.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVDEAE26bwCGD1Cor7RNOPGXX3WzNDRps',
    appId: '1:894628467468:ios:99713a4f5ddfc1beb32f29',
    messagingSenderId: '894628467468',
    projectId: 'flutter-project-fc411',
    databaseURL: 'https://flutter-project-fc411-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-project-fc411.appspot.com',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVDEAE26bwCGD1Cor7RNOPGXX3WzNDRps',
    appId: '1:894628467468:ios:99713a4f5ddfc1beb32f29',
    messagingSenderId: '894628467468',
    projectId: 'flutter-project-fc411',
    databaseURL: 'https://flutter-project-fc411-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-project-fc411.appspot.com',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbHd6NI4vW4KRwm1Z2dY-h0wmTmiKTH_Q',
    appId: '1:894628467468:web:4e83dd848bab6f82b32f29',
    messagingSenderId: '894628467468',
    projectId: 'flutter-project-fc411',
    authDomain: 'flutter-project-fc411.firebaseapp.com',
    databaseURL: 'https://flutter-project-fc411-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-project-fc411.appspot.com',
    measurementId: 'G-YQ1BKDLXN7',
  );

}