final products = [
  {
    'id': '0',
    'title': 'Men\'s Nike Shoes',
    'price': 65,
    'imageUrl': 'assets/images/shoes_4.png',
    'company': 'Nike',
    'sizes': [37, 38, 39, 40],
  },
  {
    'id': '1',
    'title': 'nike Shoes',
    'price': 55,
    'imageUrl': 'assets/images/shoes_12.jpg',
    'company': 'nike',
    'sizes': [37, 38, 39, 40],
  },
  {
    'id': '2',
    'title': 'nike\'s Shoes',
    'price': 75,
    'imageUrl': 'assets/images/shoes_6.jpg',
    'company': 'nike',
    'sizes': [37, 38, 39, 40],
  },
  {
    'id': '3',
    'title': 'Puma Shoes',
    'price': 60,
    'imageUrl': 'assets/images/shoes_7.jpg',
    'company': 'Puma',
    'sizes': [37, 38, 39, 40],
  },
  
  {
    'id': '5',
    'title': 'nike Shoes',
    'price': 55,
    'imageUrl': 'assets/images/shoes_10.jpg',
    'company': 'nike',
    'sizes': [37, 38, 39, 40],
  },
  {
    'id': '6',
    'title': 'Puma Shoes',
    'price': 55,
    'imageUrl': 'assets/images/shoes_11.jpg',
    'company': 'nike',
    'sizes': [37, 38, 39, 40],
  },
  {
    'id': '7',
    'title': 'nike Shoes',
    'price': 55,
    'imageUrl': 'assets/images/shoes_12.jpg',
    'company': 'nike',
    'sizes': [37, 38, 39, 40],
  },
  {
    'id': '8',
    'title': 'nike Shoes',
    'price': 55,
    'imageUrl': 'assets/images/shoes_28.jpg',
    'company': 'nike',
    'sizes': [37, 38, 39, 40],
  },
  {
    'id': '9',
    'title': 'nike Shoes',
    'price': 55,
    'imageUrl': 'assets/images/shoes_10.jpg',
    'company': 'nike',
    'sizes': [37, 38, 39, 40],
  },
  {
    'id': '10',
    'title': 'nike Shoes',
    'price': 55,
    'imageUrl': 'assets/images/shoes_11.jpg',
    'company': 'nike',
    'sizes': [37, 38, 39, 40],
  },
  {
    'id': '11',
    'title': 'nike Shoes',
    'price': 55,
    'imageUrl': 'assets/images/shoes_12.jpg',
    'company': 'nike',
    'sizes': [37, 38, 39, 40],
  },
  {
    'id': '12',
    'title': 'nike Shoes',
    'price': 55,
    'imageUrl': 'assets/images/shoes_13.jpg',
    'company': 'nike',
    'sizes': [37, 38, 39, 40],
  },
  {
    'id': '13',
    'title': 'nike Shoes',
    'price': 55,
    'imageUrl': 'assets/images/shoes_14.jpg',
    'company': 'Puma',
    'sizes': [37, 38, 39, 40],
  },
  {
    'id': '14',
    'title': 'Men\'s Nike Shoes',
    'price': 65,
    'imageUrl': 'assets/images/shoes_20.jpg',
    'company': 'Nike',
    'sizes': [37, 38, 39, 40],
  },
  {
    'id': '15',
    'title': 'Men\'s Nike Shoes',
    'price': 65,
    'imageUrl': 'assets/images/shoes_17.jpg',
    'company': 'Nike',
    'sizes': [37, 38, 39, 40],
  },
  {
    'id': '16',
    'title': 'Men\'s Nike Shoes',
    'price': 65,
    'imageUrl': 'assets/images/shoes_16.jpg',
    'company': 'Nike',
    'sizes': [37, 38, 39, 40],
  },
  {
    'id': '17',
    'title': 'Men\'s Nike Shoes',
    'price': 65,
    'imageUrl': 'assets/images/shoes_22.jpg',
    'company': 'Nike',
    'sizes': [37, 38, 39, 40],
  },
  {
    'id': '18',
    'title': 'Men\'s Nike Shoes',
    'price': 65,
    'imageUrl': 'assets/images/shoes_14.jpg',
    'company': 'Nike',
    'sizes': [37, 38, 39, 40],
  },
  {
    'id': '20',
    'title': 'Men\'s Nike Shoes',
    'price': 65,
    'imageUrl': 'assets/images/shoes_13.jpg',
    'company': 'Nike',
    'sizes': [37, 38, 39, 40],
  },
];
